@startuml
title Secure Map Reduce 2 - Client Monitoring
autonumber
hide footbox

participant "Client\n(c)" as C
participant "Resource\nManager\n(rm)" as RM
'participant "Node\nManager\n(nm)" as NM
'participant "Shuffle\nService\n(ss)" as SS
'participant "Application\nMaster\n(am)" as AM
participant "Client\nService\n(cs)" as CS
'participant "Application\nContainer\n(ac)" as AC #red
'participant "Application\nTask\n(at)" as T #orange
'participant "File\nSystem\n(fs)" as FS
'participant "Name\nNode\n(nn)" as NN
'participant "Data\nNode\n(dn)" as DN
participant "History\nServer\n(hs)" as HS

  'note over C,HS #green: QUESTION ?

  activate C

'1
C->RM: submitApplication\n [RPC:SASL(c-kp,rm-kp)]\n ( job-dir, serialized-secrets )\n : app-rpt{client-tkn}

'2
C->RM: queryStatus\n [???????]\n ( job-id ) \n: job-status
  note right: Until job is started RM provides status.

'3
C->RM: queryStatus\n [????????]\n ( job-id ) \n: job-status
  note right: Once job is started RM directs C to CS.

'4
C->CS: queryStatus\n [RPC:SASL(cs-tkn)]\n ( job-id ) \n: job-status
  note right: While job is running CS provides status.

note over C,HS #green: QUESTION: How does C know to switch to HS?
note over C,HS #green: QUESTION: Does this use c-hs-dt?

'5
C->HS: queryStatus\n [RPC:SASL(c-hs-dt)]\n ( job-id )\n : job-status
  note right: After job completes HS provides status to C.

  deactivate C

@enduml