@startuml
title Secure Map Reduce 2
autonumber
hide footbox

participant "Client" as C
participant "Resource\nManager" as RM
participant "Node\nManager" as NM
participant "Application\nMaster" as AM
participant "Application\nContainer" as AC
'participant "NameNode" as NN
'participant "DataNode" as DN

== Bootstrap ==

NM->RM: [] nodeStatus()
'DN->NN: heartbeat( status ): block-token-secret

== Job Definition ==

  note over C,RM: Client uses HDFS to define job.\nDo they use AM to do anything first?

== Job Submission ==

C->RM: [] submitJob()

== Job Initiation ==

RM->RM: [] allocateResource()
RM->NM: [] launchContainer( launch-spec=mr2 )
  create AM
NM->AM: [CLI as ?] exec()
  activate AM
AM->RM: [] register()

== Map Execution ==

AM->RM: [] negotateResources(): ContainerInfo
AM->NM: [] launchContainer( launch-spec=map-task )
  create AC
NM->AC: [CLI as ?] exec()
  note over AC: Does AC exec a setuid program?
  activate AC
AC->AM: [] jobStatus()
  note right: How does AC access AM?\nWhat does AC do now?
  deactivate AC
  destroy AC

== Status Query ==

C->AM: [] statusQuery()

== Reduce Execution ==

AM->RM: [] negotateResources(): ContainerInfo
AM->NM: [] launchContainer( launch-spec=map-task )
  create AC
NM->AC: [CLI as ?] exec()
  note right: Are different containers used\nfor Map and Reduce Tasks?
  activate AC
AC->AM: [] jobStatus()
  deactivate AC
  destroy AC

== Job Completion ==

deactivate AM
destroy AM

@enduml