@startuml
title Process Execution
autonumber
hide footbox

participant "Client\n(user)" as C
participant "Resource\nManager\n(yarn)" as RM
participant "Node\nManager\n(yarn)" as NM
participant "Container\nExecutor\n(root)" as CE #red
participant "Container\nLocalizer\n(user)" as CL
participant "MR\nApplication\nMaster\nContainer\n(user)" as AM
participant "MR Task\nContainer\n(user)" as T #orange

'1
C->RM: <b>submitApplication
  note right: Client defines and submits a MapReduce Job
  activate RM

'2
RM->NM: <b>startContainer
  note right: Starts an allocated container for the MR ApplicationMaster
  activate NM
  deactivate RM

'3
  create CE
NM->CE: <b>exec</b> [as yarn]
  note left: Launch native setuid executable to switch user
  activate CE

'4
  create CL
CE->CL: <b>exec</b> [as user]
  note left: Copies user private files required to run AM to local disk
  deactivate CE

'5
  create CE
NM->CE: <b>exec</b> [as yarn]
  note left: Launch native setuid executable to switch user
  activate CE

'6
  create AM
CE->AM: <b>exec</b> [as user]
  note left: Executes the MR ApplicationMaster
  deactivate NM
  activate AM
  deactivate CE

'7
AM->NM: <b>startContainer
  note left: Starts an allocated container to run a Task
  activate NM

'8
  create CE
NM->CE: <b>exec</b> [as yarn]
  note left: Launch native setuid executable to switch user
  activate CE

'9
  create CL
CE->CL: <b>exec</b> [as user]
  note left: Copies user private files required to run Task to local disk
  deactivate CE

'10
  create CE
NM->CE: <b>exec</b> [as yarn]
  note left: Launch native setuid executable to switch user
  activate CE

'11
  create T
CE->T: <b>exec</b> [as user]
  note left: Executes map and reduce tasks
  deactivate CE
  deactivate NM
  deactivate T
  deactivate T
  deactivate AM

@enduml