@startuml
title Secure Map Reduce 2 - Node Manager Token Flow
autonumber
'hide footbox

'participant "Client\n(c)" as C
participant "Resource\nManager\n(rm)" as RM
'participant "History\nServer\n(hs)" as HS
participant "Node\nManager\n(nm)" as NM
'participant "Shuffle\nService\n(ss)" as SS
participant "Application\nMaster\n(am)" as AM
'participant "Client\nService\n(cs)" as CS
'participant "Application\nContainer\n(ac)" as AC #red
'participant "Task\n(t)" as T #orange
'participant "File\nSystem\n(fs)" as FS
'participant "Name\nNode\n(nn)" as NN
'participant "Data\nNode\n(dn)" as DN
'participant "Kerberos\nKDC" as KDC

'note over C,KDC #green: QUESTION ?

== Bootstrap ==

'1
RM->RM:<b>createNodeManagerTokenSecretKey()\n : nm-tkn-sk
  note right: Secret shared with NodeManagers\nto verify NodeManager Tokens.

'2
NM->RM:<b>register/heartbeat</b>( ... )\n : nm-tkn-sk, ...
  note right: Share nm-tkn-sk with NodeManagers.

== Job Submission ==

== Job Initiation ==

'3
[->RM: <b>runJob?
  note right #green: Q1: What is the mechanism by which jobs are discovered on the queue?
  activate RM

'4
RM->RM: <b>allocateResources</b>( ... )
  note right: Call to self to allocate resources for MapReduce AppMaster.
  activate RM

'5
RM->RM: <b>createNodeManagerToken\n ( nm-tkn-sk )\n : am-nm-tkn
  note right: NodeManager Token to access NodeManager and\nstart AppContainer for MapReduce AppMaster.

'6
RM<--RM: <b>:mr-rsrc-res</b>{am-nm-tkn,...}
  note right: NM Token returned from allocationResources()\nas part of AllocatedContainer.
  deactivate RM

'7
RM->NM: <b>startContainer\n [RSAT(am-nm-tkn)]\n ( ... )
  note right: SASL verifies am-nn-tkn with nn-tkn-sk
  deactivate RM

== Map Task Execution ==

'8
AM->RM: <b>allocateResources</b>( ... )
  note right: Allocate AppContainer\nfor MapTask
  activate RM

'9
RM->RM: <b>createNodeManagerToken\n ( nm-tkn-sk )\n : mt-nm-tkn
  note right: NodeManager token to access NodeManager\nand start AppContainer for MapTask.

'10
AM<--RM: <b>:mt-rsrc-res</b>{mt-nm-tkn,...}
  note right: NM Token returned\nfrom allocationResources()\nas part of AllocatedContainer.
  deactivate RM

'11
AM->NM: <b>startContainer\n [RSAT(mt-nm-tkn)]\n ( ... )
  note left: SASL verifies mt-nn-tkn with nn-tkn-sk

== Reduce Task Execution ==

'12
AM->RM: <b>allocateResources</b>( ... )
  note right: Allocate AppContainer\nfor ReduceTask
  activate RM

'13
RM->RM: <b>createNodeManagerToken\n ( nm-tkn-sk )\n : rt-nm-tkn
  note right: NodeManager Token to access NodeManager\nand start AppContainer for ReduceTask.

'14
AM<--RM: <b>:mt-rsrc-res</b>{rt-nm-tkn,...}
  note right: NM Token returned\nfrom allocationResources()\nas part of AllocatedContainer.
  deactivate RM

'15
AM->NM: <b>startContainer\n [RSAT(rt-nm-tkn)]\n ( ... )
  note left: SASL verifies rt-nn-tkn with nn-tkn-sk

@enduml                                                                                      