@startuml
title Secure Map Reduce 2 - Application Token Flow
autonumber
'hide footbox

'participant "Client\n(c)" as C
participant "Resource\nManager\n(rm)" as RM
'participant "History\nServer\n(hs)" as HS
participant "Node\nManager\n(nm)" as NM
'participant "Shuffle\nHandler\n(ss)" as SS
participant "Application\nMaster\n(am)" as AM
'participant "Client\nService\n(cs)" as CS
'participant "Application\nContainer\n(ac)" as AC #red
'participant "Task\n(t)" as T #orange
participant "File\nSystem\n(fs)" as FS
'participant "Name\nNode\n(nn)" as NN
'participant "Data\nNode\n(dn)" as DN
'participant "Kerberos\nKDC" as KDC

'note over C,DN #green: QUESTION ?

== Bootstrap ==

== Job Definition ==

== Job Submission ==

'1
'
'AMRMTokenSecretManager.generateSecret
RM->RM: <b>generateSecret</b>\n (): app-tkn-mk

== Job Initiation ==

'2
RM->RM: <b><i>createToken</i></b>\n ( app-tkn-mk ): app-tkn

'3
'AMLauncher.setupTokensAndEnv
'credentials.writeTokenStorageToStream(dob);
'container.setTokens(ByteBuffer.wrap(dob.getData(), 0,
RM->RM: <b><i>serializeTokens</i></b>\n ( app-tkn, ... )\n : rm-tokens{app-tkn,...}

'4
'NMClientImpl.startContainer
'ContainerManagerImpl.startContainer
RM->NM: <b>startContainer</b>\n [...] ( rm-tokens{app-tkn}, ... )
  note right: StartContainerRequest.ContainerLaunchContext.tokens

'5
'ContainerLaunch.call
'Credentials.writeTokenStorageToStream
NM->FS: <b><i>storeTokens</i></b>\n ( rm-tokens{app-tkn} ): rm-tokens-loc
  create AM

'6
NM->AM: <b>exec</b> [...]\n ( env{rm-tokens-loc,...}, ... )
  note left: ApplicationConstants.\nCONTAINER_TOKEN_FILE_ENV_NAME

'7
'ContainerLocalizer.runLocalization
'Credentials.readTokenStorageStream
AM->FS: <b><i>loadTokens</i></b>\n ( rm-tokens-loc )\n : rm-tokens{app-tkn,...}

'8
''ApplicationMasterService.registerApplicationMaster
AM->RM: <b>registerApplicationMaster</b>\n [RSAT(app-tkn)] (...)

== Map Task Execution ==

'9
'ApplicationMasterService.allocate
AM->RM: <b>allocate</b>\n [RSAT(app-tkn)] (...): ...

== Reduce Task Execution ==

'10
'ApplicationMasterService.allocate
AM->RM: <b>allocate</b>\n [RSAT(app-tkn)] (...): ...

== Job Completion ==

'8
''ApplicationMasterService.finishApplicationMaster
AM->RM: <b>finishApplicationMaster</b>\n [RSAT(app-tkn)] (...)

@enduml